spring:
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache.use_second_level_cache: false
        default_batch_fetch_size: 20
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: org.h2.Driver

  # Static resources reloading during development
  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
